fileVersion: 1
id: "72"
mappingDefinitions:
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
  SRC_TEMP:
    database: ""
    schema: ""
  TARGET:
    database: PRATIK
    schema: JOBPROJECTTEST
name: New Environment
type: Environment
